export const siteConfig = {
  name: "汤伟杰的个人站点",
  nameEn: "Tang Weijie's Portfolio",
  description: "汤伟杰的个人网站，包含在线简历、技术博客和项目展示。专注于 Web 全栈开发。",
  descriptionEn: "Tang Weijie's personal website featuring online resume, tech blog and project showcase. Focused on Full Stack Web Development.",
  author: "汤伟杰",
  authorEn: "Tang Weijie",
  year: 2025,
  url: "https://tangweijie-cv.vercel.app", 
  email: "leibaio@foxmail.com",
  github: "https://github.com/leibaio",
  keywords: [
    "汤伟杰",
    "Tang Weijie",
    "全栈开发",
    "Full Stack Developer",
    "前端开发",
    "后端开发",
    "Vue",
    "React",
    "Next.js",
    "Spring Boot",
    "个人简历",
    "技术博客",
  ],
};
